//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PropertyChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckPorperty {
            get {
                return ResourceManager.GetString("CheckPorperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Display Values に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearDisplayValues {
            get {
                return ResourceManager.GetString("ClearDisplayValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateTimeLabelContent {
            get {
                return ResourceManager.GetString("DateTimeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteProperties {
            get {
                return ResourceManager.GetString("DeleteProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileLists are empty! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmptyFileLists {
            get {
                return ResourceManager.GetString("EmptyFileLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Folder Is Empty! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterTargetFolderName {
            get {
                return ResourceManager.GetString("EnterTargetFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .+\.(xls|xlsx) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExcelExtentionRX {
            get {
                return ResourceManager.GetString("ExcelExtentionRX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is not Exists! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileIsNotExists {
            get {
                return ResourceManager.GetString("FileIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is not Exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FolderName is null or empty or white space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NullEmptySpace {
            get {
                return ResourceManager.GetString("NullEmptySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .+\.(xls) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldExcelExtentionRX {
            get {
                return ResourceManager.GetString("OldExcelExtentionRX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Folder! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .+\.(pdf) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PDFExtentionRX {
            get {
                return ResourceManager.GetString("PDFExtentionRX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .+\.(pptx) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PowerPointExtentinRX {
            get {
                return ResourceManager.GetString("PowerPointExtentinRX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .+\.(docx) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordExtentionRX {
            get {
                return ResourceManager.GetString("WordExtentionRX", resourceCulture);
            }
        }
    }
}
